language: python
python:
  - "3.8"
script:
  - cd tests
  - pytest --cov=./
install:
- pip install pipenv
- pipenv install --dev
- pipenv install pytest-cov
after_success:
  - bash <(curl -s https://codecov.io/bash)