MOEX_companies :
    Etalon Group: ETLN
    Globaltrans: GLTR
    HeadHunter: HHRU
    Mail.ru Group: MAIL
    MD Medical Group: MDMG
    O'KEY Group: OKEY
    Ozon: OZON
    Petropavlovsk: POGR
    Qiwi: QIWI
    TCS Group (Тинькофф): TCSG
    X5 Retail Group: FIVE
    Акрон: AKRN
    Алроса: ALRS
    Аэрофлот: AFLT
    Башнефть: BANE
    БСПб: BSPB
    ВСМПО-АВИСМА: VSMO
    ВТБ: VTBR
    Газпром: GAZP
    Газпром нефть: SIBN
    ГК Самолет: SMLT
    Группа ПИК: PIKK
    Детский мир: DSKY
    Интер РАО ЕЭС: IRAO
    Лента: LNTA
    Ленэнерго: LSNG
    ЛСР: LSRG
    Лукойл: LKOH
    М.Видео: MVID
    Магнит: MGNT
    МГТС: MGTS
    Мечел: MTLR
    МКБ: CBOM
    ММК: MAGN
    Мосбиржа: MOEX
    Мосэнерго: MSNG
    МОЭСК: MSRS
    МРСК Волги: MRKV
    МРСК Урала: MRKU
    МРСК Центра: MRKC
    МРСК Центра и Приволжья: MRKP
    МТС: MTSS
    НКНХ: NKNC
    НЛМК: NLMK
    НМТП: NMTP
    Новатэк: NVTK
    Норникель: GMKN
    ОГК-2: OGKB
    Полиметалл: POLY
    Полюс: PLZL
    Распадская: RASP
    Роснефть: ROSN
    Россети: RSTI
    Ростелеком: RTKM
    Русагро: AGRO
    Русал: RUAL
    Русгидро: HYDR
    Русская Аквакультура: AQUA
    РуссНефть: RNFT
    Сафмар: SFIN
    Сбербанк: SBER
    Северсталь: CHMF
    Система: AFKS
    Совкомфлот: FLOT
    Сургутнефтегаз: SNGS
    Татнефть: TATN
    ТГК-1: TGKA
    ТМК: TRMK
    Транснефть: TRNFP
    Фосагро: PHOR
    ФСК: FEES
    Черкизово: GCHE
    Эн+ Груп: ENPG
    Энел: ENRU
    Юнипро: UPRO
    Яндекс: YNDX
